name: medical-decision-support-system
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - tensorboard
  - pip:
      - tensorflow-gpu
      - tensorflow-datasets==4.4.0
      - kaggle
      - tensorflow-addons[tensorflow]
      - keras-tuner