name: medical-decision-support-system
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - tensorboard
  - tensorflow=2.6.0
  - tensorflow-gpu=2.6.0
  - pip:
      - tensorflow-datasets==4.4.0
      - kaggle
      - tensorflow-addons[tensorflow]
      - keras-tuner