name: medical-decision-support-system
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - tensorflow-deps
  - pandas
  - pip
  - seaborn
  - pip:
      - tensorflow-macos==2.7
      - tensorflow-datasets==4.4.0
      - kaggle
      - keras-tuner
      - lime
      - tf-explain
      - imutils